# Dependencies
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title: Luke Jefferson
tagline: General musings and learnings 
url: http://lukejefferson.com

paginate: 1

author:
  name:           Luke Jefferson
  url:            http://twitter.com/drlaj

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/drlaj/drlaj.github.io

pages_list:
  About: '/about'
  Archive: '/archive/'
